{% set version = "1.4.0" %}

package:
  name: lazy-object-proxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lazy-object-proxy/lazy-object-proxy-{{ version }}.tar.gz
  sha256: 7fb11d33d99a374e4b0c3fb20128890b9cf784ca7e4b91ecbb191d34618bd9fe

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - lazy_object_proxy
    - lazy_object_proxy.cext

about:
  home: https://github.com/ionelmc/python-lazy-object-proxy
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'A fast and thorough lazy object proxy'
  doc_url: https://python-lazy-object-proxy.readthedocs.org
  doc_source_url: https://github.com/ionelmc/python-lazy-object-proxy/blob/master/docs/index.rst
  dev_url: https://github.com/ionelmc/python-lazy-object-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
