{% set name = "lazy-object-proxy" %}
{% set version = "1.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 1f5a462d92fd0cfb82f1fab28b51bfb209fabbe6aabf7f0d51472c0c124c0c61

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=80
    - setuptools_scm >=8
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - lazy_object_proxy
    - lazy_object_proxy.cext
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - pytest-benchmark

about:
  home: https://github.com/ionelmc/python-lazy-object-proxy
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast and thorough lazy object proxy
  description: |
    A fast and thorough lazy object proxy
  doc_url: https://python-lazy-object-proxy.readthedocs.org
  dev_url: https://github.com/ionelmc/python-lazy-object-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
    - xylar
