travis:
  secure:
    BINSTAR_TOKEN: FPFmjqJgoCwydKVNZhtJPXlC4Cpxp3apJXKgLyObkc4S7BXHWmoLS99deoA7TACCmvOFLw3NBdD6ygeK5YcrWaWZOFf0vGVWg+okw15bKcTXtnRhUSuYrO3eqIFJLRYJIiIoL/sb0to7ibqlL4gKqesCZJkKoqMFBZbZUDtTIATVShrdYCSy321J3IxdcRcRDL9vT5SbzTXtvHzrBcJJLj5XGYZEQzhC8+j09yMn85yOWxrq2JXPv99/Hb05//HyM+Z82j5pynysfzjjMurvUapKCpF+OaphORQ0IMn/vcFg0gPkasK0+XjYxP+n7EztEtxA/pzygjZDKLmiAy6l3mkRpodlhJU8FQOJIeRHqrCRpgRpvT7y//cMUs5gbl5fB+6/Y/84TOS4b9B7Q382qOD42GyyiJcJFBSRElI1pMdZfa7E7vqbqGWGBPjF+CR0ddfXzmtfyIHaKzmlkaBaJjyeekAulMAe1bi49BeB5gco9ghU3+XHk0Go769eYyhiUf2+jelK5gfcLxR+2uEtJ49M82XWZXoIo1TRkfv5NKaxGb5evjgil7BWUDcjVrqXzzCL/VksBtX44kT0CXG/YzZPulN1y7xbYK12WzAs6i2gEg759s4YOac3i93C59n59SsG4qyX2fiONpT72TAvHMWntR8SPseBZJpjdkg7/ZE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
